version: '3'
services:
  main:
    build:
      context: ..
      dockerfile: docker/server.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../img/:/go/src/Frontend/img
    restart: always
